In [206]:
import numpy as np
import yfinance as yf
import pandas as pd
from nsetools import Nse

In [207]:
nse = Nse()

In [208]:
data_stock = pd.read_excel("List of Stocks case study.xlsx")

In [209]:
data_stock

         Stock Name                        SYMBOL
0    ACC LIMITED                           ACC
1    ADANI PORT & SEZ LTD                  ADANIPORTS
2    ADANI ENTERPRISES LIMITED             ADANIENT
3    ADANI POWER LTD                       ADANIPOWER
4    AMBUJA CEMENTS LTD                    AMBUJACEM
..                                    ...         ...
156  PVR LIMITED                           PVR
157  TATA CHEMICALS LTD                    TATACHEM
158  TATA MOTORS LIMITED                   TATAMOTORS
159  TATA MOTORS DVR 'A' ORD               TATAMTRDVR
160  SUN TV NETWORK LIMITED                SUNTV

[161 rows x 2 columns]

In [210]:
data_stock.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 161 entries, 0 to 160
Data columns (total 2 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Stock Name                        161 non-null    object
 1   SYMBOL                            161 non-null    object
dtypes: object(2)
memory usage: 2.6+ KB

In [211]:
data_stock.value_counts().isnull()

Stock Name                            SYMBOL
ACC LIMITED                           ACC           False
JSW STEEL LIMITED                     JSWSTEEL      False
NBCC (INDIA) LIMITED                  NBCC          False
NCC LIMITED                           NCC           False
NESTLE INDIA LIMITED                  NESTLEIND     False
                                                    ...
GLENMARK PHARMACEUTICALS              GLENMARK      False
GMR INFRASTRUCTURE LTD.               GMRINFRA      False
GODREJ CONSUMER PRODUCTS              GODREJCP      False
GRASIM INDUSTRIES LTD                 GRASIM        False
ZEE ENTERTAINMENT ENT LTD             ZEEL          False
Length: 161, dtype: bool

In [212]:
data_stock.describe

<bound method NDFrame.describe of          Stock Name                        SYMBOL
0    ACC LIMITED                           ACC
1    ADANI PORT & SEZ LTD                  ADANIPORTS
2    ADANI ENTERPRISES LIMITED             ADANIENT
3    ADANI POWER LTD                       ADANIPOWER
4    AMBUJA CEMENTS LTD                    AMBUJACEM
..                                    ...         ...
156  PVR LIMITED                           PVR
157  TATA CHEMICALS LTD                    TATACHEM
158  TATA MOTORS LIMITED                   TATAMOTORS
159  TATA MOTORS DVR 'A' ORD               TATAMTRDVR
160  SUN TV NETWORK LIMITED                SUNTV

[161 rows x 2 columns]>

In [213]:
data_stock["Stock Name                      "]

0      ACC LIMITED
1      ADANI PORT & SEZ LTD
2      ADANI ENTERPRISES LIMITED
3      ADANI POWER LTD
4      AMBUJA CEMENTS LTD
                       ...
156    PVR LIMITED
157    TATA CHEMICALS LTD
158    TATA MOTORS LIMITED
159    TATA MOTORS DVR 'A' ORD
160    SUN TV NETWORK LIMITED
Name: Stock Name                      , Length: 161, dtype: object

In [214]:
data_stock.columns=[x.strip() for x in data_stock.columns]

In [215]:
data_stock.columns

Index(['Stock Name', 'SYMBOL'], dtype='object')

In [216]:
sym = data_stock["SYMBOL"]

In [217]:
sym

0      ACC
1      ADANIPORTS
2      ADANIENT
3      ADANIPOWER
4      AMBUJACEM
          ...
156    PVR
157    TATACHEM
158    TATAMOTORS
159    TATAMTRDVR
160    SUNTV
Name: SYMBOL, Length: 161, dtype: object

In [218]:
list=[]
for df in sym:
    list.append(df)
print(type(df))

<class 'str'>

In [219]:
list_latest = [list_latest.strip() for list_latest in list]

In [220]:
list_latest

['ACC',
 'ADANIPORTS',
 'ADANIENT',
 'ADANIPOWER',
 'AMBUJACEM',
 'APOLLOHOSP',
 'ARVIND',
 'ASIANPAINT',
 'AUROPHARMA',
 'BAJFINANCE',
 'BALKRISIND',
 'BANKBARODA',
 'BANKINDIA',
 'BERGEPAINT',
 'BHEL',
 'BAJAJFINSV',
 'BOSCHLTD',
 'CADILAHC',
 'CENTURYTEX',
 'CHOLAFIN',
 'CUMMINSIND',
 'DIVISLAB',
 'DLF',
 'ENGINERSIN',
 'EQUITAS',
 'ESCORTS',
 'FEDERALBNK',
 'GODREJCP',
 'GRASIM',
 'HAVELLS',
 'HCLTECH',
 'BSOFT',
 'HDFCBANK',
 'HEXAWARE',
 'HINDPETRO',
 'CANBK',
 'HINDZINC',
 'IDEA',
 'IDFCFIRSTB',
 'CASTROLIND',
 'INDIGO',
 'INDUSINDBK',
 'INFY',
 'IOC',
 'DHFL',
 'ITC',
 'JINDALSTEL',
 'EICHERMOT',
 'JSWSTEEL',
 'JUBLFOOD',
 'JUSTDIAL',
 'KOTAKBANK',
 'EXIDEIND',
 'L&TFH',
 'LUPIN',
 'M&M',
 'GLENMARK',
 'MARICO',
 'MCDOWELL-N',
 'MCX',
 'MOTHERSUMI',
 'MRF',
 'MUTHOOTFIN',
 'NATIONALUM',
 'NCC',
 'ICICIPRULI',
 'NESTLEIND',
 'NTPC',
 'ONGC',
 'PAGEIND',
 'INFRATEL',
 'PFC',
 'PIDILITIND',
 'PNB',
 'RAMCOCEM',
 'RAYMOND',
 'RECLTD',
 'RELCAPITAL',
 'RELIANCE',
 'SAIL',
 'SIEMENS',
 'SRF',
 'SRTRANSFIN',
 'STAR',
 'TATAGLOBAL',
 'TATAPOWER',
 'TCS',
 'MGL',
 'TECHM',
 'MINDTREE',
 'TORNTPOWER',
 'UBL',
 'UJJIVAN',
 'UNIONBANK',
 'UPL',
 'VEDL',
 'VOLTAS',
 'WIPRO',
 'YESBANK',
 'AMARAJABAT',
 'NIITTECH',
 'RELINFRA',
 'APOLLOTYRE',
 'AXISBANK',
 'TITAN',
 'ASHOKLEY',
 'BAJAJ-AUTO',
 'BATAINDIA',
 'BEL',
 'BHARATFORG',
 'BIOCON',
 'BPCL',
 'BRITANNIA',
 'CESC',
 'CIPLA',
 'COALINDIA',
 'DABUR',
 'DISHTV',
 'GAIL',
 'GMRINFRA',
 'HDFC',
 'HEROMOTOCO',
 'CONCOR',
 'HINDALCO',
 'DRREDDY',
 'HINDUNILVR',
 'IBULHSGFIN',
 'IDBI',
 'IGL',
 'MANAPPURAM',
 'MFSL',
 'M&MFIN',
 'MARUTI',
 'OFSS',
 'NMDC',
 'OIL',
 'POWERGRID',
 'RBLBANK',
 'SHREECEM',
 'SUNPHARMA',
 'TATASTEEL',
 'TATAELXSI',
 'TORNTPHARM',
 'TVSMOTOR',
 'ULTRACEMCO',
 'ZEEL',
 'COLPAL',
 'ICICIBANK',
 'LICHSGFIN',
 'SBIN',
 'BHARTIARTL',
 'LT',
 'NBCC',
 'KAJARIACER',
 'PEL',
 'PETRONET',
 'PVR',
 'TATACHEM',
 'TATAMOTORS',
 'TATAMTRDVR',
 'SUNTV']

In [221]:
list_l=[]
for a in list_latest:
    a = a+".NS"
    list_l.append(a)
print(list_l)

['ACC.NS', 'ADANIPORTS.NS', 'ADANIENT.NS', 'ADANIPOWER.NS', 'AMBUJACEM.NS', 'APOLLOHOSP.NS', 'ARVIND.NS', 'ASIANPAINT.NS', 'AUROPHARMA.NS', 'BAJFINANCE.NS', 'BALKRISIND.NS', 'BANKBARODA.NS', 'BANKINDIA.NS', 'BERGEPAINT.NS', 'BHEL.NS', 'BAJAJFINSV.NS', 'BOSCHLTD.NS', 'CADILAHC.NS', 'CENTURYTEX.NS', 'CHOLAFIN.NS', 'CUMMINSIND.NS', 'DIVISLAB.NS', 'DLF.NS', 'ENGINERSIN.NS', 'EQUITAS.NS', 'ESCORTS.NS', 'FEDERALBNK.NS', 'GODREJCP.NS', 'GRASIM.NS', 'HAVELLS.NS', 'HCLTECH.NS', 'BSOFT.NS', 'HDFCBANK.NS', 'HEXAWARE.NS', 'HINDPETRO.NS', 'CANBK.NS', 'HINDZINC.NS', 'IDEA.NS', 'IDFCFIRSTB.NS', 'CASTROLIND.NS', 'INDIGO.NS', 'INDUSINDBK.NS', 'INFY.NS', 'IOC.NS', 'DHFL.NS', 'ITC.NS', 'JINDALSTEL.NS', 'EICHERMOT.NS', 'JSWSTEEL.NS', 'JUBLFOOD.NS', 'JUSTDIAL.NS', 'KOTAKBANK.NS', 'EXIDEIND.NS', 'L&TFH.NS', 'LUPIN.NS', 'M&M.NS', 'GLENMARK.NS', 'MARICO.NS', 'MCDOWELL-N.NS', 'MCX.NS', 'MOTHERSUMI.NS', 'MRF.NS', 'MUTHOOTFIN.NS', 'NATIONALUM.NS', 'NCC.NS', 'ICICIPRULI.NS', 'NESTLEIND.NS', 'NTPC.NS', 'ONGC.NS', 'PAGEIND.NS', 'INFRATEL.NS', 'PFC.NS', 'PIDILITIND.NS', 'PNB.NS', 'RAMCOCEM.NS', 'RAYMOND.NS', 'RECLTD.NS', 'RELCAPITAL.NS', 'RELIANCE.NS', 'SAIL.NS', 'SIEMENS.NS', 'SRF.NS', 'SRTRANSFIN.NS', 'STAR.NS', 'TATAGLOBAL.NS', 'TATAPOWER.NS', 'TCS.NS', 'MGL.NS', 'TECHM.NS', 'MINDTREE.NS', 'TORNTPOWER.NS', 'UBL.NS', 'UJJIVAN.NS', 'UNIONBANK.NS', 'UPL.NS', 'VEDL.NS', 'VOLTAS.NS', 'WIPRO.NS', 'YESBANK.NS', 'AMARAJABAT.NS', 'NIITTECH.NS', 'RELINFRA.NS', 'APOLLOTYRE.NS', 'AXISBANK.NS', 'TITAN.NS', 'ASHOKLEY.NS', 'BAJAJ-AUTO.NS', 'BATAINDIA.NS', 'BEL.NS', 'BHARATFORG.NS', 'BIOCON.NS', 'BPCL.NS', 'BRITANNIA.NS', 'CESC.NS', 'CIPLA.NS', 'COALINDIA.NS', 'DABUR.NS', 'DISHTV.NS', 'GAIL.NS', 'GMRINFRA.NS', 'HDFC.NS', 'HEROMOTOCO.NS', 'CONCOR.NS', 'HINDALCO.NS', 'DRREDDY.NS', 'HINDUNILVR.NS', 'IBULHSGFIN.NS', 'IDBI.NS', 'IGL.NS', 'MANAPPURAM.NS', 'MFSL.NS', 'M&MFIN.NS', 'MARUTI.NS', 'OFSS.NS', 'NMDC.NS', 'OIL.NS', 'POWERGRID.NS', 'RBLBANK.NS', 'SHREECEM.NS', 'SUNPHARMA.NS', 'TATASTEEL.NS', 'TATAELXSI.NS', 'TORNTPHARM.NS', 'TVSMOTOR.NS', 'ULTRACEMCO.NS', 'ZEEL.NS', 'COLPAL.NS', 'ICICIBANK.NS', 'LICHSGFIN.NS', 'SBIN.NS', 'BHARTIARTL.NS', 'LT.NS', 'NBCC.NS', 'KAJARIACER.NS', 'PEL.NS', 'PETRONET.NS', 'PVR.NS', 'TATACHEM.NS', 'TATAMOTORS.NS', 'TATAMTRDVR.NS', 'SUNTV.NS']

In [222]:
list_l

['ACC.NS',
 'ADANIPORTS.NS',
 'ADANIENT.NS',
 'ADANIPOWER.NS',
 'AMBUJACEM.NS',
 'APOLLOHOSP.NS',
 'ARVIND.NS',
 'ASIANPAINT.NS',
 'AUROPHARMA.NS',
 'BAJFINANCE.NS',
 'BALKRISIND.NS',
 'BANKBARODA.NS',
 'BANKINDIA.NS',
 'BERGEPAINT.NS',
 'BHEL.NS',
 'BAJAJFINSV.NS',
 'BOSCHLTD.NS',
 'CADILAHC.NS',
 'CENTURYTEX.NS',
 'CHOLAFIN.NS',
 'CUMMINSIND.NS',
 'DIVISLAB.NS',
 'DLF.NS',
 'ENGINERSIN.NS',
 'EQUITAS.NS',
 'ESCORTS.NS',
 'FEDERALBNK.NS',
 'GODREJCP.NS',
 'GRASIM.NS',
 'HAVELLS.NS',
 'HCLTECH.NS',
 'BSOFT.NS',
 'HDFCBANK.NS',
 'HEXAWARE.NS',
 'HINDPETRO.NS',
 'CANBK.NS',
 'HINDZINC.NS',
 'IDEA.NS',
 'IDFCFIRSTB.NS',
 'CASTROLIND.NS',
 'INDIGO.NS',
 'INDUSINDBK.NS',
 'INFY.NS',
 'IOC.NS',
 'DHFL.NS',
 'ITC.NS',
 'JINDALSTEL.NS',
 'EICHERMOT.NS',
 'JSWSTEEL.NS',
 'JUBLFOOD.NS',
 'JUSTDIAL.NS',
 'KOTAKBANK.NS',
 'EXIDEIND.NS',
 'L&TFH.NS',
 'LUPIN.NS',
 'M&M.NS',
 'GLENMARK.NS',
 'MARICO.NS',
 'MCDOWELL-N.NS',
 'MCX.NS',
 'MOTHERSUMI.NS',
 'MRF.NS',
 'MUTHOOTFIN.NS',
 'NATIONALUM.NS',
 'NCC.NS',
 'ICICIPRULI.NS',
 'NESTLEIND.NS',
 'NTPC.NS',
 'ONGC.NS',
 'PAGEIND.NS',
 'INFRATEL.NS',
 'PFC.NS',
 'PIDILITIND.NS',
 'PNB.NS',
 'RAMCOCEM.NS',
 'RAYMOND.NS',
 'RECLTD.NS',
 'RELCAPITAL.NS',
 'RELIANCE.NS',
 'SAIL.NS',
 'SIEMENS.NS',
 'SRF.NS',
 'SRTRANSFIN.NS',
 'STAR.NS',
 'TATAGLOBAL.NS',
 'TATAPOWER.NS',
 'TCS.NS',
 'MGL.NS',
 'TECHM.NS',
 'MINDTREE.NS',
 'TORNTPOWER.NS',
 'UBL.NS',
 'UJJIVAN.NS',
 'UNIONBANK.NS',
 'UPL.NS',
 'VEDL.NS',
 'VOLTAS.NS',
 'WIPRO.NS',
 'YESBANK.NS',
 'AMARAJABAT.NS',
 'NIITTECH.NS',
 'RELINFRA.NS',
 'APOLLOTYRE.NS',
 'AXISBANK.NS',
 'TITAN.NS',
 'ASHOKLEY.NS',
 'BAJAJ-AUTO.NS',
 'BATAINDIA.NS',
 'BEL.NS',
 'BHARATFORG.NS',
 'BIOCON.NS',
 'BPCL.NS',
 'BRITANNIA.NS',
 'CESC.NS',
 'CIPLA.NS',
 'COALINDIA.NS',
 'DABUR.NS',
 'DISHTV.NS',
 'GAIL.NS',
 'GMRINFRA.NS',
 'HDFC.NS',
 'HEROMOTOCO.NS',
 'CONCOR.NS',
 'HINDALCO.NS',
 'DRREDDY.NS',
 'HINDUNILVR.NS',
 'IBULHSGFIN.NS',
 'IDBI.NS',
 'IGL.NS',
 'MANAPPURAM.NS',
 'MFSL.NS',
 'M&MFIN.NS',
 'MARUTI.NS',
 'OFSS.NS',
 'NMDC.NS',
 'OIL.NS',
 'POWERGRID.NS',
 'RBLBANK.NS',
 'SHREECEM.NS',
 'SUNPHARMA.NS',
 'TATASTEEL.NS',
 'TATAELXSI.NS',
 'TORNTPHARM.NS',
 'TVSMOTOR.NS',
 'ULTRACEMCO.NS',
 'ZEEL.NS',
 'COLPAL.NS',
 'ICICIBANK.NS',
 'LICHSGFIN.NS',
 'SBIN.NS',
 'BHARTIARTL.NS',
 'LT.NS',
 'NBCC.NS',
 'KAJARIACER.NS',
 'PEL.NS',
 'PETRONET.NS',
 'PVR.NS',
 'TATACHEM.NS',
 'TATAMOTORS.NS',
 'TATAMTRDVR.NS',
 'SUNTV.NS']

In [223]:
data = yf.download(list_l,'2022-08-1')

[***                    6%                       ]  10 of 161 completedGot error from yahoo api for ticker MOTHERSUMI.NS, Error: {'code': 'Not Found', 'description': 'No data found, symbol may be delisted'}
[********              16%                       ]  25 of 161 completedGot error from yahoo api for ticker NIITTECH.NS, Error: {'code': 'Not Found', 'description': 'No data found, symbol may be delisted'}
Got error from yahoo api for ticker INFRATEL.NS, Error: {'code': 'Not Found', 'description': 'No data found, symbol may be delisted'}
[*************         28%                       ]  45 of 161 completedGot error from yahoo api for ticker TATAGLOBAL.NS, Error: {'code': 'Not Found', 'description': 'No data found, symbol may be delisted'}
[*****************     35%                       ]  56 of 161 completedGot error from yahoo api for ticker CADILAHC.NS, Error: {'code': 'Not Found', 'description': 'No data found, symbol may be delisted'}
[**********************63%*****                  ]  101 of 161 completedGot error from yahoo api for ticker DHFL.NS, Error: {'code': 'Not Found', 'description': 'No data found, symbol may be delisted'}
[*********************100%***********************]  161 of 161 completed

7 Failed downloads:
- MOTHERSUMI.NS: No data found for this date range, symbol may be delisted
- NIITTECH.NS: No data found for this date range, symbol may be delisted
- INFRATEL.NS: No data found for this date range, symbol may be delisted
- TATAGLOBAL.NS: No data found for this date range, symbol may be delisted
- CADILAHC.NS: No data found for this date range, symbol may be delisted
- DHFL.NS: No data found for this date range, symbol may be delisted
- HEXAWARE.NS: No data found for this date range, symbol may be delisted

E_data = ('INFRATEL.NS','DHFL.NS','HEXAWARE.NS','MOTHERSUMI.NS','NIITTECH.NS','CADILAHC.NS','TATAGLOBAL.NS')

In [224]:
data

              Adj Close                                           \
                 ACC.NS  ADANIENT.NS ADANIPORTS.NS ADANIPOWER.NS
Date
2022-08-01  2226.550049  2660.149902    801.250000    321.850006
2022-08-02  2227.649902  2683.649902    802.299988    328.549988
2022-08-03  2236.399902  2711.399902    807.200012    339.600006
2022-08-04  2222.300049  2723.600098    807.250000    347.250000
2022-08-05  2254.800049  2698.399902    810.250000    332.049988
...                 ...          ...           ...           ...
2022-10-31  2390.300049  3347.449951    823.549988    334.899994
2022-11-01  2428.050049  3575.699951    841.799988    348.899994
2022-11-02  2440.000000  3580.699951    833.400024    343.149994
2022-11-03  2455.350098  3590.399902    833.849976    336.750000
2022-11-04  2480.699951  3833.250000    862.900024    346.850006

                                                                               \
           AMARAJABAT.NS AMBUJACEM.NS APOLLOHOSP.NS APOLLOTYRE.NS   ARVIND.NS
Date
2022-08-01    501.600006   375.399994   4276.398438    222.100006   99.449997
2022-08-02    506.149994   378.649994   4314.095215    227.350006  100.500000
2022-08-03    505.799988   381.750000   4298.288086    228.500000   97.099998
2022-08-04    505.350006   381.250000   4383.804199    232.199997   96.400002
2022-08-05    504.600006   382.649994   4362.163574    230.000000   96.199997
...                  ...          ...           ...           ...         ...
2022-10-31    513.049988   532.950012   4517.500000    290.700012   92.800003
2022-11-01    515.299988   544.049988   4511.350098    292.950012   93.099998
2022-11-02    513.349976   545.000000   4383.100098    288.649994   91.750000
2022-11-03    519.750000   539.500000   4395.000000    286.450012   91.550003
2022-11-04    569.400024   558.599976   4362.600098    288.899994   95.750000

                        ...  Volume                                        \
           ASHOKLEY.NS  ...  UBL.NS UJJIVAN.NS ULTRACEMCO.NS UNIONBANK.NS
Date                    ...
2022-08-01  154.250000  ...  323535    2501492        414339      6828607
2022-08-02  148.699997  ...  277200    1594722        274658     16386463
2022-08-03  148.500000  ...  281088    1031775        266360      6896291
2022-08-04  145.899994  ...  210593    1228969        275815      6043811
2022-08-05  144.949997  ...  141440    1696312        741250      5705713
...                ...  ...     ...        ...           ...          ...
2022-10-31  153.300003  ...  193635     313672        538107     20844507
2022-11-01  149.750000  ...  207318     711438        429855     17543556
2022-11-02  149.449997  ...  178552     615746        255634     10868384
2022-11-03  148.050003  ...  301220    1127074        217701     15499173
2022-11-04  146.699997  ...   88519    1400692        646067     23723264


             UPL.NS   VEDL.NS VOLTAS.NS WIPRO.NS YESBANK.NS   ZEEL.NS
Date
2022-08-01  7797234  10114375   1297725  5182874  283753874  14510639
2022-08-02  5611299  11012297   1028956  8456213  984540451   7244357
2022-08-03  3058290   9843948   4034577  6017469  380839570   6947723
2022-08-04  1781136   9463532   1270775  8894567  234484381   5878522
2022-08-05  1828490  13811834   1993658  6483793  111491714   5339729
...             ...       ...       ...      ...        ...       ...
2022-10-31  2733496  12599029   1960573  3319191   35745633   5845813
2022-11-01  5060223   9070975   1623970  5770098  111914590   5961641
2022-11-02  1949252  20332664   3102411  3358307   53832667   5384989
2022-11-03  1665899  19690261   3067654  5156238  140562676   5604967
2022-11-04  3317371  52117064   2805029  4510958   97207364   4225829

[65 rows x 966 columns]

In [226]:
data.columns

MultiIndex([('Adj Close',        'ACC.NS'),
            ('Adj Close',   'ADANIENT.NS'),
            ('Adj Close', 'ADANIPORTS.NS'),
            ('Adj Close', 'ADANIPOWER.NS'),
            ('Adj Close', 'AMARAJABAT.NS'),
            ('Adj Close',  'AMBUJACEM.NS'),
            ('Adj Close', 'APOLLOHOSP.NS'),
            ('Adj Close', 'APOLLOTYRE.NS'),
            ('Adj Close',     'ARVIND.NS'),
            ('Adj Close',   'ASHOKLEY.NS'),
            ...
            (   'Volume',        'UBL.NS'),
            (   'Volume',    'UJJIVAN.NS'),
            (   'Volume', 'ULTRACEMCO.NS'),
            (   'Volume',  'UNIONBANK.NS'),
            (   'Volume',        'UPL.NS'),
            (   'Volume',       'VEDL.NS'),
            (   'Volume',     'VOLTAS.NS'),
            (   'Volume',      'WIPRO.NS'),
            (   'Volume',    'YESBANK.NS'),
            (   'Volume',       'ZEEL.NS')],
           length=966)

In [255]:
list_x=list_l.copy()

In [254]:
list_4=[]
list_3=[]
for list_2 in list_x:
    if(list_2=='INFRATEL.NS' or list_2=='DHFL.NS' or list_2=='HEXAWARE.NS' or list_2=='MOTHERSUMI.NS' or list_2=='NIITTECH.NS' or list_2=='CADILAHC.NS' or list_2=='TATAGLOBAL.NS'):
        list_4.append(list_2)
    else: 
        list_3.append(list_2)
print(list_3)
print(list_4)

['ACC.NS', 'ADANIPORTS.NS', 'ADANIENT.NS', 'ADANIPOWER.NS', 'AMBUJACEM.NS', 'APOLLOHOSP.NS', 'ARVIND.NS', 'ASIANPAINT.NS', 'AUROPHARMA.NS', 'BAJFINANCE.NS', 'BALKRISIND.NS', 'BANKBARODA.NS', 'BANKINDIA.NS', 'BERGEPAINT.NS', 'BHEL.NS', 'BAJAJFINSV.NS', 'BOSCHLTD.NS', 'CENTURYTEX.NS', 'CHOLAFIN.NS', 'CUMMINSIND.NS', 'DIVISLAB.NS', 'DLF.NS', 'ENGINERSIN.NS', 'EQUITAS.NS', 'ESCORTS.NS', 'FEDERALBNK.NS', 'GODREJCP.NS', 'GRASIM.NS', 'HAVELLS.NS', 'HCLTECH.NS', 'BSOFT.NS', 'HDFCBANK.NS', 'HINDPETRO.NS', 'CANBK.NS', 'HINDZINC.NS', 'IDEA.NS', 'IDFCFIRSTB.NS', 'CASTROLIND.NS', 'INDIGO.NS', 'INDUSINDBK.NS', 'INFY.NS', 'IOC.NS', 'ITC.NS', 'JINDALSTEL.NS', 'EICHERMOT.NS', 'JSWSTEEL.NS', 'JUBLFOOD.NS', 'JUSTDIAL.NS', 'KOTAKBANK.NS', 'EXIDEIND.NS', 'L&TFH.NS', 'LUPIN.NS', 'M&M.NS', 'GLENMARK.NS', 'MARICO.NS', 'MCDOWELL-N.NS', 'MCX.NS', 'MRF.NS', 'MUTHOOTFIN.NS', 'NATIONALUM.NS', 'NCC.NS', 'ICICIPRULI.NS', 'NESTLEIND.NS', 'NTPC.NS', 'ONGC.NS', 'PAGEIND.NS', 'PFC.NS', 'PIDILITIND.NS', 'PNB.NS', 'RAMCOCEM.NS', 'RAYMOND.NS', 'RECLTD.NS', 'RELCAPITAL.NS', 'RELIANCE.NS', 'SAIL.NS', 'SIEMENS.NS', 'SRF.NS', 'SRTRANSFIN.NS', 'STAR.NS', 'TATAPOWER.NS', 'TCS.NS', 'MGL.NS', 'TECHM.NS', 'MINDTREE.NS', 'TORNTPOWER.NS', 'UBL.NS', 'UJJIVAN.NS', 'UNIONBANK.NS', 'UPL.NS', 'VEDL.NS', 'VOLTAS.NS', 'WIPRO.NS', 'YESBANK.NS', 'AMARAJABAT.NS', 'RELINFRA.NS', 'APOLLOTYRE.NS', 'AXISBANK.NS', 'TITAN.NS', 'ASHOKLEY.NS', 'BAJAJ-AUTO.NS', 'BATAINDIA.NS', 'BEL.NS', 'BHARATFORG.NS', 'BIOCON.NS', 'BPCL.NS', 'BRITANNIA.NS', 'CESC.NS', 'CIPLA.NS', 'COALINDIA.NS', 'DABUR.NS', 'DISHTV.NS', 'GAIL.NS', 'GMRINFRA.NS', 'HDFC.NS', 'HEROMOTOCO.NS', 'CONCOR.NS', 'HINDALCO.NS', 'DRREDDY.NS', 'HINDUNILVR.NS', 'IBULHSGFIN.NS', 'IDBI.NS', 'IGL.NS', 'MANAPPURAM.NS', 'MFSL.NS', 'M&MFIN.NS', 'MARUTI.NS', 'OFSS.NS', 'NMDC.NS', 'OIL.NS', 'POWERGRID.NS', 'RBLBANK.NS', 'SHREECEM.NS', 'SUNPHARMA.NS', 'TATASTEEL.NS', 'TATAELXSI.NS', 'TORNTPHARM.NS', 'TVSMOTOR.NS', 'ULTRACEMCO.NS', 'ZEEL.NS', 'COLPAL.NS', 'ICICIBANK.NS', 'LICHSGFIN.NS', 'SBIN.NS', 'BHARTIARTL.NS', 'LT.NS', 'NBCC.NS', 'KAJARIACER.NS', 'PEL.NS', 'PETRONET.NS', 'PVR.NS', 'TATACHEM.NS', 'TATAMOTORS.NS', 'TATAMTRDVR.NS', 'SUNTV.NS']
['CADILAHC.NS', 'HEXAWARE.NS', 'DHFL.NS', 'MOTHERSUMI.NS', 'INFRATEL.NS', 'TATAGLOBAL.NS', 'NIITTECH.NS']

In [256]:
data_latest = yf.download(list_3,'2022-08-1')

[*********************100%***********************]  154 of 154 completed

In [257]:
data_latest

              Adj Close                                           \
                 ACC.NS  ADANIENT.NS ADANIPORTS.NS ADANIPOWER.NS
Date
2022-08-01  2226.550049  2660.149902    801.250000    321.850006
2022-08-02  2227.649902  2683.649902    802.299988    328.549988
2022-08-03  2236.399902  2711.399902    807.200012    339.600006
2022-08-04  2222.300049  2723.600098    807.250000    347.250000
2022-08-05  2254.800049  2698.399902    810.250000    332.049988
...                 ...          ...           ...           ...
2022-10-31  2390.300049  3347.449951    823.549988    334.899994
2022-11-01  2428.050049  3575.699951    841.799988    348.899994
2022-11-02  2440.000000  3580.699951    833.400024    343.149994
2022-11-03  2455.350098  3590.399902    833.849976    336.750000
2022-11-04  2480.699951  3833.250000    862.900024    346.850006

                                                                               \
           AMARAJABAT.NS AMBUJACEM.NS APOLLOHOSP.NS APOLLOTYRE.NS   ARVIND.NS
Date
2022-08-01    501.600006   375.399994   4276.398438    222.100006   99.449997
2022-08-02    506.149994   378.649994   4314.095215    227.350006  100.500000
2022-08-03    505.799988   381.750000   4298.288086    228.500000   97.099998
2022-08-04    505.350006   381.250000   4383.804199    232.199997   96.400002
2022-08-05    504.600006   382.649994   4362.163574    230.000000   96.199997
...                  ...          ...           ...           ...         ...
2022-10-31    513.049988   532.950012   4517.500000    290.700012   92.800003
2022-11-01    515.299988   544.049988   4511.350098    292.950012   93.099998
2022-11-02    513.349976   545.000000   4383.100098    288.649994   91.750000
2022-11-03    519.750000   539.500000   4395.000000    286.450012   91.550003
2022-11-04    569.400024   558.599976   4362.600098    288.899994   95.750000

                        ...  Volume                                        \
           ASHOKLEY.NS  ...  UBL.NS UJJIVAN.NS ULTRACEMCO.NS UNIONBANK.NS
Date                    ...
2022-08-01  154.250000  ...  323535    2501492        414339      6828607
2022-08-02  148.699997  ...  277200    1594722        274658     16386463
2022-08-03  148.500000  ...  281088    1031775        266360      6896291
2022-08-04  145.899994  ...  210593    1228969        275815      6043811
2022-08-05  144.949997  ...  141440    1696312        741250      5705713
...                ...  ...     ...        ...           ...          ...
2022-10-31  153.300003  ...  193635     313672        538107     20844507
2022-11-01  149.750000  ...  207318     711438        429855     17543556
2022-11-02  149.449997  ...  178552     615746        255634     10868384
2022-11-03  148.050003  ...  301220    1127074        217701     15499173
2022-11-04  146.699997  ...   88519    1400692        646067     23723264


             UPL.NS   VEDL.NS VOLTAS.NS WIPRO.NS YESBANK.NS   ZEEL.NS
Date
2022-08-01  7797234  10114375   1297725  5182874  283753874  14510639
2022-08-02  5611299  11012297   1028956  8456213  984540451   7244357
2022-08-03  3058290   9843948   4034577  6017469  380839570   6947723
2022-08-04  1781136   9463532   1270775  8894567  234484381   5878522
2022-08-05  1828490  13811834   1993658  6483793  111491714   5339729
...             ...       ...       ...      ...        ...       ...
2022-10-31  2733496  12599029   1960573  3319191   35745633   5845813
2022-11-01  5060223   9070975   1623970  5770098  111914590   5961641
2022-11-02  1949252  20332664   3102411  3358307   53832667   5384989
2022-11-03  1665899  19690261   3067654  5156238  140562676   5604967
2022-11-04  3317371  52117064   2805029  4510958   97207364   4225829

[65 rows x 924 columns]

In [258]:
data_latest.columns

MultiIndex([('Adj Close',        'ACC.NS'),
            ('Adj Close',   'ADANIENT.NS'),
            ('Adj Close', 'ADANIPORTS.NS'),
            ('Adj Close', 'ADANIPOWER.NS'),
            ('Adj Close', 'AMARAJABAT.NS'),
            ('Adj Close',  'AMBUJACEM.NS'),
            ('Adj Close', 'APOLLOHOSP.NS'),
            ('Adj Close', 'APOLLOTYRE.NS'),
            ('Adj Close',     'ARVIND.NS'),
            ('Adj Close',   'ASHOKLEY.NS'),
            ...
            (   'Volume',        'UBL.NS'),
            (   'Volume',    'UJJIVAN.NS'),
            (   'Volume', 'ULTRACEMCO.NS'),
            (   'Volume',  'UNIONBANK.NS'),
            (   'Volume',        'UPL.NS'),
            (   'Volume',       'VEDL.NS'),
            (   'Volume',     'VOLTAS.NS'),
            (   'Volume',      'WIPRO.NS'),
            (   'Volume',    'YESBANK.NS'),
            (   'Volume',       'ZEEL.NS')],
           length=924)

In [227]:
q = nse.get_quote("ACC")

In [228]:
q

{'pricebandupper': 2700.85,
 'symbol': 'ACC',
 'applicableMargin': 15.48,
 'bcEndDate': None,
 'totalSellQuantity': 241.0,
 'adhocMargin': None,
 'companyName': 'ACC Limited',
 'marketType': 'N',
 'exDate': '04-APR-22',
 'bcStartDate': None,
 'css_status_desc': 'Listed',
 'dayHigh': 2514.95,
 'basePrice': 2455.35,
 'securityVar': 11.98,
 'pricebandlower': 2209.85,
 'sellQuantity5': None,
 'sellQuantity4': None,
 'sellQuantity3': None,
 'cm_adj_high_dt': '14-SEP-22',
 'sellQuantity2': None,
 'dayLow': 2459.3,
 'sellQuantity1': 241.0,
 'quantityTraded': 585433.0,
 'pChange': 1.15,
 'totalTradedValue': 14552.46,
 'deliveryToTradedQuantity': 25.46,
 'totalBuyQuantity': None,
 'averagePrice': 2485.76,
 'indexVar': None,
 'cm_ffm': 20962.97,
 'purpose': 'DIVIDEND - RS 58 PER SHARE',
 'buyPrice2': None,
 'secDate': '04-Nov-2022 00:00:00',
 'buyPrice1': None,
 'high52': 2785.0,
 'previousClose': 2455.35,
 'ndEndDate': None,
 'low52': 1900.0,
 'buyPrice4': None,
 'buyPrice3': None,
 'recordDate': '05-APR-22',
 'deliveryQuantity': 149032.0,
 'buyPrice5': None,
 'priceBand': 'No Band',
 'extremeLossMargin': 3.5,
 'cm_adj_low_dt': '07-MAR-22',
 'varMargin': 11.98,
 'sellPrice1': 2480.7,
 'sellPrice2': None,
 'totalTradedVolume': 585433.0,
 'sellPrice3': None,
 'sellPrice4': None,
 'sellPrice5': None,
 'change': 28.15,
 'surv_indicator': None,
 'ndStartDate': None,
 'buyQuantity4': None,
 'isExDateFlag': False,
 'buyQuantity3': None,
 'buyQuantity2': None,
 'buyQuantity1': None,
 'series': 'EQ',
 'faceValue': 10.0,
 'buyQuantity5': None,
 'closePrice': 2480.7,
 'open': 2462.0,
 'isinCode': 'INE012A01025',
 'lastPrice': 2483.5}

In [ ]:
data.to_excel("Output of Stock Closing Price.xlsx")

In [259]:
data_latest.to_excel("Output_of_Stock_Closing_Price.xlsx")